feat: Use env variable to control the animated spider and the profiler.
UN-OCHA/ocha-api-site pull request #11
Opened 2022-11-16 00:41 UTC by cafuego

So we can turn them off on production.

See https://github.com/UN-OCHA/tools-ansible/pull/989

Refs: OHA-3

2022-11-16 07:50 UTC, attiks commented on config/packages/web_profiler.yaml
> +        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
This is only active on dev

2022-11-16 07:52 UTC, attiks requested changes

2022-11-16 07:52 UTC, attiks commented on config/packages/web_profiler.yaml
> +        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
Same

2022-11-16 07:52 UTC, attiks commented on config/packages/api_platform.yaml
> +    show_webby: '%env(bool:PLATFORM_SHOW_WEBBY)%'
Better to just disable it

2022-11-16 07:52 UTC, attiks commented on .env
> +PLATFORM_SHOW_WEBBY=false
Better to use `.env.prod`

2022-11-17 01:36 UTC, cafuego commented on config/packages/api_platform.yaml
> +    show_webby: '%env(bool:PLATFORM_SHOW_WEBBY)%'
```suggestion
    show_webby: false
```

2022-11-17 01:36 UTC, cafuego commented on .env
> +###< ocha/ops ###
```suggestion
```

2022-11-17 01:37 UTC, cafuego commented on config/packages/web_profiler.yaml
> +        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
```suggestion
        toolbar: true
```

2022-11-17 01:37 UTC, cafuego commented on config/packages/web_profiler.yaml
> +        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
```suggestion
        toolbar: true
```

2022-11-18 08:43 UTC, attiks approved these changes

2022-11-21 04:30 UTC, merged